name: 'Add labels to an issue or PR'
description: 'An action to add labels to an issue or PR.'
author: 'Bright Ran'

inputs:
  repository:
    description: 'The name of the repository which the pull request is in. For example, ActionsRML/latest-commit-on-PR'
    required: true
    default: ${{ github.repository }}
  issue_number:
    description: 'The number of the issue or PR.'
    required: true
    default: ${{ github.event.pull_request.number }}
  token:
    description: 'Personal access token (PAT) used to authenticate.'
    default: ${{ github.token }}

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'filter'
  color: 'green'
